#-----------------------------------------------------------------#
## è‡ªç”¨Clashé…ç½®æ¨¡æ¿
## ä½œè€…ï¼šCarefree Montage
## æ›´æ–°ï¼š2024-04-15
## æ³¨æ„ï¼šè¯¥é…ç½®ä¸ºè‡ªç”¨çš„æ¨¡æ¿ï¼Œå¯èƒ½ä¸é€‚ç”¨äºæ¯ä¸ªäººï¼Œè¯·è‡ªè¡Œæ ¹æ®è‡ªå·±çš„æƒ…å†µä¿®æ”¹
#-----------------------------------------------------------------#

# è®¢é˜…é“¾æ¥ 
config:
# Clashä¸æ”¯æŒæŸäº›è®¢é˜…é“¾æ¥æå–èŠ‚ç‚¹(ä¾‹å¦‚CFW v.0.20.39)
# è¯·ç”¨Clash Verge/Clash Nyanpasuç­‰æ–°å†…æ ¸çš„å®¢æˆ·ç«¯
# å¦‚æœä¸€å®šè¦ç”¨Clashï¼Œè¯·è‡ªè¡Œè½¬æ¢è®¢é˜…ä¸ºæ”¯æŒproxy-providersçš„é“¾æ¥
  subscription-url: &url "https://yourURL....."

mixed-port: 7890
allow-lan: #false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
    enable: true
    ipv6: true
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    fake-ip-filter: [time.apple.com, time.windows.com, pool.ntp.org]
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://1.1.1.1/dns-query', 'https://1.1.1.2/dns-query', 'https://208.67.222.222/dns-query', 'https://9.9.9.9/dns-query', 'https://45.11.45.11/dns-query', 'tls://8.8.4.4:853', 'https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://dns.twnic.tw/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }

# ä»£ç†é›† - æä¾›èŠ‚ç‚¹
proxy-providers:

  Node-Info: # åç§°éšæ„
    type: http
    path: ./myConfig/nodes/Node-Info.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'å‰©ä½™|åˆ°æœŸ'   
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Node-HK:
    type: http
    path: ./myConfig/nodes/Node-HK.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'é¦™æ¸¯|hk|hong kong|hongkong|ğŸ‡­ğŸ‡°'
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Node-JP:
    type: http
    path: ./myConfig/nodes/Node-JP.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'æ—¥æœ¬|jp|japan|ğŸ‡¯ğŸ‡µ'
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Node-SG:
    type: http
    path: ./myConfig/nodes/Node-SG.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'æ–°åŠ å¡|sg|singapore|ğŸ‡¸ğŸ‡¬'
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Node-US:
    type: http
    path: ./myConfig/nodes/Node-US.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'ç¾å›½|us|usa|america|united states|unitedstates|ğŸ‡ºğŸ‡²|ğŸ‡ºğŸ‡¸'
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Node-DE:
    type: http
    path: ./myConfig/nodes/Node-DE.yaml
    url: *url
    interval: 1800
    # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹å…³é”®å­—
    filter: 'å¾·å›½|de|ger|germany|ğŸ‡©ğŸ‡ª'
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

# ç­–ç•¥ç»„
proxy-groups:
  # æ ¹æ®è‡ªå·±çš„è®¢é˜…å†…å®¹ä¿®æ”¹
  - { name: 'ğŸš€ ä»£ç†èŠ‚ç‚¹'  , type: select, use: ['Node-Info', 'Node-HK', 'Node-JP', 'Node-SG', 'Node-US', 'Node-DE'] }
  - { name: 'ğŸ›¸ Google'   , type: select, use: ['Node-US'] }
  - { name: 'ğŸ“º Netflix'  , type: select, use: ['Node-SG', 'Node-HK', 'Node-JP', 'Node-US'] }
  - { name: 'ğŸ” Copilot'     , type: select, proxies: ['ğŸš€ ä»£ç†èŠ‚ç‚¹', 'ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿'], use: ['Node-HK', 'Node-JP', 'Node-SG', 'Node-US', 'Node-DE'] }
  - { name: 'ğŸ¤– OpenAI'   , type: select, use: ['Node-SG', 'Node-US'] }
  - { name: 'ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿'  , type: select, proxies: ['DIRECT'] }
  - { name: 'ğŸ Apple'    , type: select, proxies: ['ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿', 'ğŸš€ ä»£ç†èŠ‚ç‚¹'], use: ['Node-HK', 'Node-JP', 'Node-SG', 'Node-US', 'Node-DE'] }
  - { name: 'ğŸªŸ Microsoft', type: select, proxies: ['ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿','ğŸš€ ä»£ç†èŠ‚ç‚¹'], use: ['Node-HK', 'Node-JP', 'Node-SG', 'Node-US', 'Node-DE'] }
  - { name: 'âŒï¸ å¹¿å‘Šæ‹¦æˆª'  , type: select, proxies: ['REJECT'] }

# è§„åˆ™é›†
rule-providers:
  # ä»£ç†
    google:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/PROXY/Google.yaml"
      path: ./myConfig/ruleset/proxy/google.yaml
      interval: 86400

    netflix:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/PROXY/Netflix.yaml"
      path: ./myConfig/ruleset/proxy/netflix.yaml
      interval: 86400
  
    Copilot:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/PROXY/Copilot.yaml"
      path: ./myConfig/ruleset/proxy/Copilot.yaml
      interval: 86400

    openai:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/PROXY/OpenAI.yaml"
      path: ./myConfig/ruleset/proxy/openai.yaml
      interval: 86400

  # ç›´è¿
    china:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/DIRECT/China.yaml"
      path: ./myConfig/ruleset/direct/china.yaml
      interval: 86400

    apple:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/DIRECT/Apple.yaml"
      path: ./myConfig/ruleset/direct/apple.yaml
      interval: 86400
  
    microsoft:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/DIRECT/Microsoft.yaml"
      path: ./myConfig/ruleset/direct/microsoft.yaml
      interval: 86400

  # å¹¿å‘Šæ‹¦æˆª
    reject:
      type: http
      behavior: classical
      url: "https://cdn.jsdelivr.net/gh/CarefreeMontage/proxyrules-cm@main/Clash/REJECT/ADBlock.yaml"
      path: ./myConfig/ruleset/reject/rejectAD.yaml
      interval: 86400

  #......ä¹‹åæœ‰éœ€è¦å†åŠ 

# å¼•ç”¨è§„åˆ™é›†ã€ç­–ç•¥ç»„
rules:
  - DOMAIN,clash.razord.top,ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿
  - DOMAIN,yacd.haishan.me,ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿
  # å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,reject,âŒï¸ å¹¿å‘Šæ‹¦æˆª
  # apple
  - RULE-SET,apple,ğŸ Apple
  # microsoft
  - RULE-SET,Copilot,ğŸ” Copilot
  - RULE-SET,microsoft,ğŸªŸ Microsoft
  # google
  - RULE-SET,google,ğŸ›¸ Google
  # netflix
  - RULE-SET,netflix,ğŸ“º Netflix
  # openai
  - RULE-SET,openai,ğŸ¤– OpenAI
  # china
  - RULE-SET,china,ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿
  - GEOIP,CN,ğŸ‡¨ğŸ‡³ å›½å†…ç›´è¿
  # å…¶ä»–ä¸åœ¨è§„åˆ™å†…çš„
  - MATCH,ğŸš€ ä»£ç†èŠ‚ç‚¹
